### ISSUE TITLE
Requesting Updated Mupen64Plus Version

### ISSUE THREAD

**Issue by Shmoopi** [hylian-modding/ModLoader64-Platform-Deps#1]
# Mupen64Plus Version

The last build uses an unknown version of Mupen64Plus that may be outdated.

## Request

If possible, can you open-source the .pak build process / steps so it can be updated, or provide an updated version?

**Comment by ParchmentWolf** [comment]
The modloader isnt making use of any of the features newer mupen provides, it isnt necessary to update it -- and modifications had to be made to the base mupen libraries to interop properly with the expanded featuresets. Even if you repacked a newer mupen for no benefit you would only break other things.

**Comment by Shmoopi** [comment]
Thank you for the quick response!  And good to know!  Either way, is it possible to get build steps in order to contribute?

**Comment by ParchmentWolf** [comment]
best i can give you is this:
https://github.com/hylian-modding/ModLoader64-Mupen64Plus

Its surely not the specific repo that they were using since I know they added sfml and some other goofy stuff into the binding, but I had build instructions if you can find the specific repo they had for that.

**Comment by Shmoopi** [comment]
Much appreciated, thank you!
